services:
  - type: web
    name: kambaz-node-server-app
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SERVER_ENV
        value: production
      - key: CLIENT_URL
        value: https://kambaz-next-js-david-conrad-l8f3affjx.vercel.app
      - key: SERVER_URL
        value: https://with-mongo-dwde.onrender.com